### ISSUE TITLE
usage

### ISSUE THREAD

**Issue by vinnitu** [maxtaco/iced-error#2]
I my test script index.iced

```icedcoffeescript
{make_esc} = require "iced-error"

bar = (cb) ->
  esc = make_esc cb, "bar"
  # ...
  return cb "failed" # if statement
  # ...

foo = (cb) ->
  esc = make_esc cb, "foo"
  # ...
  await bar esc defer result
  cb null, "success"

do ->
  await foo defer error, result
  console.log {error, result}
```

I am waiting for {error: "failed", result: undefined},
but received

```
TypeError: Cannot call method 'push' of undefined
  at ipush (/home/user/project/node_modules/iced-error/index.js:82:23)
  at /home/user/project/node_modules/iced-error/index.js:95:11
  at bar (/home/user/project/index.iced:8:10)
  at /home/user/project/index.iced:17:9
  at foo (/home/user/project/index.iced:17:3)
  at console.log.error (/home/user/project/index.iced:21:9)
  at /home/user/project/index.iced:21:3
  at Object.<anonymous> (/home/user/project/index.iced:20:1)
  at Object.<anonymous> (/home/user/project/index.iced:1:1)
  at Module._compile (module.js:456:26)
```

What is the right way to use iced-error?

thx

**Comment by maxtaco** [comment]
More or less.  You just have to be certain to return Error objects and not strings...

So `return cb new Error "failed"` is likely what you want instead of what you have...
